version: '3.3'

services:
  app:
    container_name: app
    build: ./app
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - rabbitmq

  notification_consumer:
    container_name: notification_consumer
    build: ./notification_consumer
    restart: always
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
    ports:
        - 5672:5672
        - 8080:15672

